# Generated by Django 5.1.4 on 2025-03-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('ngo', 'NGO')], default='volunteer', max_length=10),
        ),
    ]
